name: Test CI/CD Workflow

on:
  workflow_dispatch: 
jobs:
  test-job:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print current date
        run: date
